GET http://localhost:5210/games

###
GET http://localhost:5210/games/1

###
POST http://localhost:5210/games
Content-Type: application/json

{
    "name": "Dark Souls II",
    "genreId": 2,
    "price": 27.99,
    "releaseDate": "2014-03-11"
}

###
PUT http://localhost:5210/games/1
Content-Type: application/json

{
    "name": "Dark Souls I",
    "genreId": 2,
    "price": 19.99,
    "releaseDate": "2011-09-22"
}

###
DELETE http://localhost:5210/games/1

###
GET http://localhost:5210/genres
