GET http://localhost:5210/games

###
GET http://localhost:5210/games?genreId=2

###
GET http://localhost:5210/games?search=Elden

###
GET http://localhost:5210/games?genreId=2&search=Elden

###
GET http://localhost:5210/games?page=1&pageSize=10

###
GET http://localhost:5210/games?sort=price

###
GET http://localhost:5210/games?sort=price_desc

###
GET http://localhost:5210/games?sort=name

###
GET http://localhost:5210/games?sort=releasedate

###
GET http://localhost:5210/games/1

###
POST http://localhost:5210/games
Content-Type: application/json

{
    "name": "Game 5",
    "genreId": 2,
    "price": 5.99,
    "releaseDate": "2024-03-15"
}

###
PUT http://localhost:5210/games/1
Content-Type: application/json

{
    "name": "Dark Souls I",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "2011-09-22"
}

###
DELETE http://localhost:5210/games/5

###
GET http://localhost:5210/genres
